const fs = require('fs');
const path = require('path');

// Configuration
const VERSION_FILE = path.join(__dirname, '../src/lib/version.json');
const RELEASES_DIR = path.join(__dirname, '../docs/releases');
const COMMIT_SUMMARY_FILE = path.join(__dirname, '../commit-summary.txt');

// Args: node scripts/publish.js [type] [message] [reference] [steps]
const type = process.argv[2] || 'Enhancement'; 
const message = process.argv[3] || 'General improvements and stability fixes.';
const reference = process.argv[4] || ''; // e.g. #123 or #L500-800
const steps = process.argv[5] || ''; // Reproduce/Verify steps

function getGitInfo() {
    try {
        const { execSync } = require('child_process');
        const hash = execSync('git rev-parse --short HEAD').toString().trim();
        const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
        const remote = execSync('git remote get-url origin').toString().trim();
        const repo = remote.split('/').pop().replace('.git', '');
        return { hash, branch, repo };
    } catch (e) {
        return { hash: 'n/a', branch: 'n/a', repo: 'BaitulMal-2026v1' };
    }
}

const { updateVersion: performVersionUpdate } = require('./version-utils');

function updateVersion() {
    if (!fs.existsSync(RELEASES_DIR)) {
        fs.mkdirSync(RELEASES_DIR, { recursive: true });
    }
    const previousVersion = fs.existsSync(VERSION_FILE) 
        ? JSON.parse(fs.readFileSync(VERSION_FILE, 'utf8')).version 
        : 'n/a';

    const newVersion = performVersionUpdate(type, message, reference, steps);
    const entry = JSON.parse(fs.readFileSync(VERSION_FILE, 'utf8')).history[0];

    // Create Separate Release Doc
    createReleaseDoc(entry);

    // Auto-trigger Documentation Generation (AFTER version update so docs see the NEW version)
    try {
        const { execSync } = require('child_process');
        console.log('🔄 Regenerating Institutional Documentation Suite...');
        // Pass previous version as env var so documentation generators can archive correctly
        execSync(`node scripts/generate-index.js`, { env: { ...process.env, PREVIOUS_VERSION: previousVersion } });
        execSync(`node scripts/generate-user-guides.js`, { env: { ...process.env, PREVIOUS_VERSION: previousVersion } });
        execSync(`node scripts/generate-architecture.js`, { env: { ...process.env, PREVIOUS_VERSION: previousVersion } });
    } catch (e) {
        console.error('Failed to generate documentation suite:', e.message);
    }

    // Generate Commit Summary File
    generateCommitSummary(entry);
}

function generateCommitSummary(entry) {
    const summary = `release: v${entry.version}\n\nType: ${entry.type}\nMessage: ${entry.message}\nReference: ${entry.reference || 'n/a'}\nBranch: ${entry.branch}\nCommit: ${entry.commit}\n\nVerification Steps:\n${entry.steps || 'Manual verification required.'}`;
    fs.writeFileSync(COMMIT_SUMMARY_FILE, summary);
    console.log(`📝 Commit summary generated: ${path.basename(COMMIT_SUMMARY_FILE)}`);
}

function createReleaseDoc(entry) {
    const filename = `release-v${entry.version}.md`;
    const filePath = path.join(RELEASES_DIR, filename);
    const dateStr = new Date(entry.date).toLocaleString();

    let content = `# 🚀 Release Documentation - v${entry.version}\n\n`;
    content += `**Date:** ${dateStr}\n`;
    content += `**Repo:** \`${entry.repo}\`\n`;
    content += `**Branch:** \`${entry.branch}\`\n`;
    content += `**Commit:** \`${entry.commit}\`\n`;
    if (entry.reference) {
        content += `**Reference:** \`${entry.reference}\`\n`;
    }
    content += `\n## 📋 Build Summary\n\n`;

    // Categorize
    const isBug = entry.type.toLowerCase() === 'bug';
    const isEnhancement = entry.type.toLowerCase() === 'enhancement';
    const isFeature = entry.type.toLowerCase() === 'feature' || entry.type.toLowerCase() === 'new feature';

    const msgWithRef = entry.reference ? `${entry.message} (${entry.reference})` : entry.message;

    content += `### 🐞 Bugs Fixed\n${isBug ? `- ${msgWithRef}` : '*No critical bugs reported in this build.*'}\n\n`;
    content += `### ⚡ Enhancements\n${isEnhancement ? `- ${msgWithRef}` : '*No infrastructure enhancements in this build.*'}\n\n`;
    content += `### ✨ New Features\n${isFeature ? `- ${msgWithRef}` : '*No new feature modules in this build.*'}\n\n`;
    
    content += `## 🔍 Verification Steps\n\n`;
    if (entry.steps) {
        content += `${entry.steps}\n\n`;
    } else {
        content += `1. Review the modified code in the referenced commit (\`${entry.commit}\`).\n`;
        content += `2. Verify that the build version \`${entry.version}\` is displayed correctly in the application footer.\n`;
        content += `3. Perform regression testing on the affected module: \`${entry.type}\`.\n\n`;
    }

    content += `---\n*Generated by Institutional Release Automator*`;

    fs.writeFileSync(filePath, content);
    console.log(`📄 Separate release document created: releases/${filename}`);
}

updateVersion();
